import { useSession, signOut } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { FileUploadInput } from "~/components/form/FIleUploadInput";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { Inventory } from "./inventory";
import { Header } from "~/components/header";
import CounterPage from "./users/cashier";

export default function POSTabs() {
  const { data: sessionData } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!sessionData) router.push("/");
  });

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col bg-white text-primary-foreground dark:bg-[#121212]">
        <div className=" flex flex-col gap-2  py-3">
          {/* Header */}
          <Header />
          {/* Body */}
          <div className="container flex flex-col space-y-2">
            <Tabs
              defaultValue="pos"
              className="flex min-h-screen flex-col bg-transparent"
            >
              <TabsList className=" flex w-80 justify-between self-center bg-white text-[#979797] dark:bg-gradient-to-b dark:from-[#2e026d] dark:to-[#15162c] sm:w-96">
                <TabsTrigger className="rounded-full" value="pos">
                  POS
                </TabsTrigger>
                <TabsTrigger className="rounded-full" value="dashboard">
                  Dashboard
                </TabsTrigger>
                <TabsTrigger className="rounded-full" value="orders">
                  Orders
                </TabsTrigger>
                <TabsTrigger className="rounded-full" value="inventory">
                  Inventory
                </TabsTrigger>
              </TabsList>

              <TabsContent value="pos">
                {/* POS */}
                <CounterPage />
              </TabsContent>

              <TabsContent value="dashboard">
                <Card>
                  <CardHeader>
                    <CardTitle>Dashboard</CardTitle>
                    <CardDescription>
                      Change your Dashboard here. Click save when you're done.
                    </CardDescription>
                  </CardHeader>
                </Card>
              </TabsContent>

              <TabsContent value="orders">
                <Card>
                  <CardHeader>
                    <CardTitle>ONIICHAN</CardTitle>
                    <CardDescription>Customer</CardDescription>
                    <Card className="px-3 py-10"></Card>
                    <Card className="px-3 py-10"></Card>
                    <Button className="bg-pink-500 hover:bg-pink-600 rounded-lg text-white">
                      Done
                    </Button>
                  </CardHeader>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>JER</CardTitle>
                    <CardDescription>Customer</CardDescription>
                    <Card className="px-3 py-10"></Card>
                    <Card className="px-3 py-10"></Card>
                    <Button className="bg-pink-500 hover:bg-pink-600 rounded-lg text-white">
                      Done
                    </Button>
                  </CardHeader>
                </Card>
              </TabsContent>

              <TabsContent value="inventory">
                <Inventory />
              </TabsContent>
            </Tabs>
            He
          </div>
        </div>
      </main>
    </>
  );
}
