import Head from "next/head";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";

export default function Home() {
  return (
    <>
      <Head>
        <title>Streamline</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-8 px-4 py-16">
          <div className="flex w-full max-w-md flex-col gap-4">
            <Label htmlFor="file" className="text-lg font-semibold text-white">
              Upload an Excel File
            </Label>
            <div className="flex w-full flex-col items-stretch gap-2">
              <div className="w-full">
                <Input
                  id="file"
                  type="file"
                  className="w-full rounded-lg bg-gray-200 px-4 py-2"
                />
                <span className="text-sm text-gray-400">
                  File formats: .xlsx, .xls
                </span>
              </div>
              <Button className="rounded-lg bg-blue-500 text-white hover:bg-blue-600">
                Submit
              </Button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
