import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import DisplayUserList from "~/components/admin";
import { Button } from "~/components/ui/button";

export default function Admin() {
  const { data: sessionData } = useSession();
  const router = useRouter();

  function isNormalUser() {
 
    if (sessionData && sessionData.user.name !== "gigachad")
      return true;
  }

  useEffect(() => {
    if (sessionData) router.push("/admin/dashboard");
    if (isNormalUser()) router.push("/");
  });

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {sessionData ? (
        <main className="flex min-h-screen flex-col bg-[#121212] text-primary-foreground">
          <div className="container flex flex-col items-start justify-start gap-12  py-10">
            <div className=" item-center flex w-full flex-row place-content-between">
              <div>
                <p className=" text-4xl font-semibold">Streamline Admin</p>
                <p className="text-lg text-secondary ">
                  {sessionData.user.name}
                </p>
              </div>

              <Button
                className="text-lg font-semibold"
                size="lg"
                variant="ghost"
                onClick={() => void signOut({ callbackUrl: "/admin" })}
              >
                Sign out
              </Button>
            </div>
            <div className="container flex flex-col space-y-2">
              <header className="text-xl font-bold">Users</header>
              <DisplayUserList />
            </div>
          </div>
        </main>
      ) : (
        <p>No session</p>
      )}
    </>
  );
}
