"use client";

import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Button } from "~/components/ui/button";

export default function Admin() {
  const { data: sessionData } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!sessionData) router.push("/admin");
  });

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {sessionData ? (
        <main className="text-primary-foreground flex min-h-screen flex-col bg-[#121212]">
          <div className="container flex flex-col items-start justify-start gap-12  py-10">
            <div className=" item-center flex w-full flex-row place-content-between">
              <div>
                <p className=" text-4xl font-semibold">Streamline Admin</p>
                <p className="text-secondary text-lg ">
                  {sessionData.user.name}
                </p>
              </div>

              <Button
                className="text-lg font-semibold"
                size="lg"
                variant="ghost"
                onClick={() => void signOut({ callbackUrl: "/admin/dashboard" })}
              >
                Sign out
              </Button>
            </div>
            <div>
              <p className=" text-lg ">Should display content here</p>
            </div>
          </div>
        </main>
      ) : (
        <p>No session</p>
      )}
    </>
  );
}
