import { useSession } from "next-auth/react";
import Head from "next/head";
import { SignInForm } from "~/components/form/signInForm";

export default function Admin() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" flex min-h-screen flex-col items-center justify-center bg-[#121212]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <SignInForm />
        </div>
      </main>
    </>
  );
}
